# Generated by Django 3.1.4 on 2020-12-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_monitor', '0002_auto_20201213_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='isFraud',
            field=models.BooleanField(default=False),
        ),
    ]
