# Generated by Django 3.1.4 on 2020-12-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_monitor', '0003_transaction_isfraud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='TransactionID',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Сard6',
            field=models.CharField(max_length=10),
        ),
    ]
