# Generated by Django 3.1.4 on 2020-12-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_monitor', '0004_auto_20201213_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Сard6',
            new_name='Card6',
        ),
    ]
